version: "2.1"
services:
  kafka:
    image: jeqo/apache-kafka:0.10.1.0-2.11
    links:
      - zookeeper
    depends_on:
      - zookeeper
    
    command:
      - /bin/bash -c " /opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic kafka_test && /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties"
      
  zookeeper:
    image: jeqo/apache-zookeeper:3.4.8
  
  
  python-kafka-consumer:
    image: python-kafka:latest
    volumes:
      - ./python-kafka:/code
    command:
      -  /code/sample/python-consumer.py
  
  python-kafka-producer:
    image: python-kafka:latest
    volumes:
      - ./python-kafka:/code
    command:
      -  /code/sample/python-producer.py
