FROM jeqo/apache-kafka:0.10.1.0-2.11
ENV TOPIC_NAME kafka_test
WORKDIR /opt/kafka
RUN bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic $TOPIC_NAME 
CMD bin/kafka-server-start.sh config/server.properties